---
- name: Set up nodejs, npm, pm2 and python in an EC2
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

  roles:
    - configure-server
